FROM node:10.11-alpine

RUN mkdir -p /server

COPY ./package.json /server/


WORKDIR /server

RUN npm install -qy

## wait for mongoDB
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait

CMD /wait && ["npm", "start"] 